### PR TITLE
Fixed bugs as they popped up

### PR DESCRIPTION
**Pull request by MatthewWolff**
added the -o flag because it was required to specify the name of something
added some quotations
standardized the python scripts in keeping with PEP8 standards
created a make file, which can allow the setup.sh and resetFiles.sh scripts to be moved alongside the other scripts (as "make" and "make clean" can be called instead)
renamed the README.md file to be standard

### CODE REVIEW

**Comment by MatthewWolff** [comment]
differences between the runAll.sh files need to be looked at, as i don't know what's up with lines 59 and 60 in mine — i thought i had the freshest copy from the repo, but those lines aren't there

**Comment by MatthewWolff** [comment]
I also had to change a line of the python code to metaReads = int(float([x.strip() for x in line.split(" ")][1])) because it wasn't stripping the string before and it caused an exception on my end

**Comment by MatthewWolff** [comment]
changed _vs_ to -vs- because that's simply how my files were named

**Comment by sstevens2** [comment]
Hey @MatthewWolff.  Thanks for this pull request.  
I really like the changes, esp the addition of a makefile.
Unfortunately I didn't see this until after I'd made some changes and your formatting changes (though I appreciate the push to follow PEP8) make it difficult to compare the functional differences. 

Perhaps you can rebase your branch to start with my latest version?

**Comment by MatthewWolff** [comment]
* cloned the most recent version from your github and conformed the python files to PEP8 standards
* rewrote resetFiles.sh and setup.sh to be less verbose with same functionality. 
* the error message previously in setup.sh didn't seem to have much practical value, and I only say that with the thought that folder creation is pretty harmless 
  * changed to simply chime "Set-up complete" as an indicator to user that it had executed

**Comment by sstevens2** [comment]
Looks good, I will merge.

**Pull request merged**
